# run on all hosts
- hosts: all
  tasks:

  - name: clone git
    ansible.builtin.git:
      repo: https://github.com/2105-may24-devops/danielb-project0.git
      dest: ~/danielb-project0

  - name: setup venv and install requirements
    pip:
      requirements: ~/danielb-project0/requirements.txt
      virtualenv: ~/venv